# -*- coding: utf-8 -*-
# Generated by Django 2.0.2 on 2018-03-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration that adds unique constraint to the Email field of User model."""

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that email already exists."},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
